// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-va5aSPzTTL5t9eSTy-HNjxcsZVbKPo',
    appId: '1:186530813213:web:e78bf92a83f2c0a15c3df4',
    messagingSenderId: '186530813213',
    projectId: 'chatapp-3a422',
    authDomain: 'chatapp-3a422.firebaseapp.com',
    storageBucket: 'chatapp-3a422.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3PDuHhm-VygHHaUg4rFpZUZSoFKIZJc',
    appId: '1:186530813213:android:86a184397a9a23475c3df4',
    messagingSenderId: '186530813213',
    projectId: 'chatapp-3a422',
    storageBucket: 'chatapp-3a422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_NQ-NF56fIuoWjg_luvJVKD2xSAVf-8',
    appId: '1:186530813213:ios:f0a08a4748a7b85b5c3df4',
    messagingSenderId: '186530813213',
    projectId: 'chatapp-3a422',
    storageBucket: 'chatapp-3a422.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_NQ-NF56fIuoWjg_luvJVKD2xSAVf-8',
    appId: '1:186530813213:ios:f0a08a4748a7b85b5c3df4',
    messagingSenderId: '186530813213',
    projectId: 'chatapp-3a422',
    storageBucket: 'chatapp-3a422.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ-va5aSPzTTL5t9eSTy-HNjxcsZVbKPo',
    appId: '1:186530813213:web:2b5e5e7ae4aee9cc5c3df4',
    messagingSenderId: '186530813213',
    projectId: 'chatapp-3a422',
    authDomain: 'chatapp-3a422.firebaseapp.com',
    storageBucket: 'chatapp-3a422.appspot.com',
  );
}
